### PR TITLE
Actuator board schematic rev A

### PR DESCRIPTION
**Pull request by SyrianSpock**
I finally finished the design of the schematic, GitHub is not very appropriate for electronics review, but more formal than Slack to manage the repo properly IMO. It can also be reviewed in KiCaD directly, but useless commit-by-commit as there is one big commit with the changes to the schematic. Do we need 2 digital inputs? I can add this easily since the MCU's I/Os are not full yet.

[Schematic in PDF](https://github.com/cvra/actuator-board/files/4081839/actuator-board.pdf)

### CODE REVIEW

**Comment by msplr** [comment]
Didn't we decide for 2 sensors and 2 pumps+solenoids per board to reduce the number of boards needed?

**Review by antoinealb — CHANGES_REQUESTED** [review]
Here is our complete review (with @nuft)

[20200120141639421.pdf](https://github.com/cvra/actuator-board/files/4086114/20200120141639421.pdf)

**Comment by SyrianSpock** [comment]
changed and added 2 solenoids and 1 sensor
[Schematic A.2](https://github.com/cvra/actuator-board/files/4110763/actuator-board.pdf)

**Comment by SyrianSpock** [comment]
updated with missing corrections
[Schematic A.3](https://github.com/cvra/actuator-board/files/4112763/actuator-board.pdf)

**Comment by antoinealb** [comment]
My notes on the last schematic:

* Not sure if C15 should be on the board. We will probably put a large capacitor inline with the wiring no ? If not, it should have a value.
* U5 and U6 should be two different part numbers, as they *MUST* have different I2C addresses, and those are defined by the part number. Please also add a comment with their I2C address.
* Why is there a voltage divider on the analog inputs ?
* Digikey part numbers should be in a different field (See U4), not appended in the reference field as free form text.
* Flyback diodes should be Shottkys.

**Comment by SyrianSpock** [comment]
> Not sure if C15 should be on the board. We will probably put a large capacitor inline with the wiring no? If not, it should have a value.

I don't know how we will wire the board, but I put it as a placeholder, I'll remove it.

> U5 and U6 should be two different part numbers, as they MUST have different I2C addresses, and those are defined by the part number. Please also add a comment with their I2C address.

Still need to find the right parts in Digikey

> Why is there a voltage divider on the analog inputs?

it's how I'm used to doing ADC input AF filters

> Digikey part numbers should be in a different field (See U4), not appended in the reference field as free form text.

OK

> Flyback diodes should be Shottkys.

OK

**Comment by antoinealb** [comment]
> it's how I'm used to doing ADC input AF filters

The divider is not part of the filter, it is to adapt the input range. Do we know what input range we will have ?

**Comment by SyrianSpock** [comment]
> The divider is not part of the filter, it is to adapt the input range. Do we know what input range we will have?

I just impose 3.6V max, but we need to choose the resistor (max voltage) ASAP. Otherwise, the wiring will be ugly :nauseated_face:

**Comment by msplr** [comment]
Merge now. PCB is ordered

**Pull request merged**
